
// MLB team names mapping
export const mlbNames: Record<string, string> = {
  'ARI': 'Diamondbacks',
  'ATL': 'Braves',
  'BAL': 'Orioles',
  'BOS': 'Red Sox',
  'CHC': 'Cubs',
  'CWS': 'White Sox',
  'CHW': 'White Sox',
  'CIN': 'Reds',
  'CLE': 'Guardians',
  'COL': 'Rockies',
  'DET': 'Tigers',
  'HOU': 'Astros',
  'KC': 'Royals',
  'KCR': 'Royals',
  'LAA': 'Angels',
  'LAD': 'Dodgers',
  'MIA': 'Marlins',
  'MIL': 'Brewers',
  'MIN': 'Twins',
  'NYM': 'Mets',
  'NYY': 'Yankees',
  'OAK': 'Athletics',
  'ATH': 'Athletics',
  'PHI': 'Phillies',
  'PIT': 'Pirates',
  'SD': 'Padres',
  'SDP': 'Padres',
  'SF': 'Giants',
  'SFG': 'Giants',
  'SEA': 'Mariners',
  'STL': 'Cardinals',
  'TB': 'Rays',
  'TBR': 'Rays',
  'TEX': 'Rangers',
  'TOR': 'Blue Jays',
  'WSH': 'Nationals',
  'WSN': 'Nationals',
};
