
// MLB team logos mapping
export const mlbLogos: Record<string, string> = {
  'ARI': 'https://www.mlbstatic.com/team-logos/109.svg',
  'ATL': 'https://www.mlbstatic.com/team-logos/144.svg',
  'BAL': 'https://www.mlbstatic.com/team-logos/110.svg',
  'BOS': 'https://www.mlbstatic.com/team-logos/111.svg',
  'CHC': 'https://www.mlbstatic.com/team-logos/112.svg',
  'CWS': 'https://www.mlbstatic.com/team-logos/145.svg',
  'CHW': 'https://www.mlbstatic.com/team-logos/145.svg',
  'CIN': 'https://www.mlbstatic.com/team-logos/113.svg',
  'CLE': 'https://www.mlbstatic.com/team-logos/114.svg',
  'COL': 'https://www.mlbstatic.com/team-logos/115.svg',
  'DET': 'https://www.mlbstatic.com/team-logos/116.svg',
  'HOU': 'https://www.mlbstatic.com/team-logos/117.svg',
  'KC': 'https://www.mlbstatic.com/team-logos/118.svg',
  'KCR': 'https://www.mlbstatic.com/team-logos/118.svg',
  'LAA': 'https://www.mlbstatic.com/team-logos/108.svg',
  'LAD': 'https://www.mlbstatic.com/team-logos/119.svg',
  'MIA': 'https://www.mlbstatic.com/team-logos/146.svg',
  'MIL': 'https://www.mlbstatic.com/team-logos/158.svg',
  'MIN': 'https://www.mlbstatic.com/team-logos/142.svg',
  'NYM': 'https://www.mlbstatic.com/team-logos/121.svg',
  'NYY': 'https://www.mlbstatic.com/team-logos/147.svg',
  'OAK': 'https://www.mlbstatic.com/team-logos/133.svg',
  'ATH': 'https://www.mlbstatic.com/team-logos/133.svg',
  'PHI': 'https://www.mlbstatic.com/team-logos/143.svg',
  'PIT': 'https://www.mlbstatic.com/team-logos/134.svg',
  'SD': 'https://www.mlbstatic.com/team-logos/135.svg',
  'SDP': 'https://www.mlbstatic.com/team-logos/135.svg',
  'SF': 'https://www.mlbstatic.com/team-logos/137.svg',
  'SFG': 'https://www.mlbstatic.com/team-logos/137.svg',
  'SEA': 'https://www.mlbstatic.com/team-logos/136.svg',
  'STL': 'https://www.mlbstatic.com/team-logos/138.svg',
  'TB': 'https://www.mlbstatic.com/team-logos/139.svg',
  'TBR': 'https://www.mlbstatic.com/team-logos/139.svg',
  'TEX': 'https://www.mlbstatic.com/team-logos/140.svg',
  'TOR': 'https://www.mlbstatic.com/team-logos/141.svg',
  'WSH': 'https://www.mlbstatic.com/team-logos/120.svg',
  'WSN': 'https://www.mlbstatic.com/team-logos/120.svg',
};
