
// NFL team logos mapping
export const nflLogos: Record<string, string> = {
  'ARI': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/u9fltoslqdsyao8cpm0k',
  'ATL': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/d8m7hzpsbrl6pnqht8op',
  'BAL': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/ucsdijmddsqcj1i0nmur',
  'BUF': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/giphcy6ie9mxbnldntsf',
  'CAR': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/ervfzgrqdqpkfcjhu8jq',
  'CHI': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/ra0poua3hivselqbgcbs',
  'CIN': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/okxpteoliyayufypqalq',
  'CLE': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/fgbn8acp4opvyxk13dcy',
  'DAL': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/ieid8hoygzdlmzo0yhqr',
  'DEN': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/t2jwlmj1tmpzcqzf2eav',
  'DET': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/ocvxwnapdvwevupe4tpr',
  'GB': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/k5oxnyitwseuo27mnod9',
  'GNB': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/k5oxnyitwseuo27mnod9',
  'HOU': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/bpx2n7s8m4u2pz8dbu5m',
  'IND': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/keenyn6qtrzngbcq8bre',
  'JAX': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/qykmj6xgtzpyc7xlzyra',
  'KC': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/ujdzcqep1oxcgbwgz3bz',
  'LV': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/gzcojbzcyjgubgyb6xf2',
  'OAK': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/gzcojbzcyjgubgyb6xf2',
  'LAC': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/dhfidtn8jrumakbogeu4',
  'SD': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/dhfidtn8jrumakbogeu4',
  'LAR': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/ayvngv0oygf5ym1p3mhp',
  'STL': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/ayvngv0oygf5ym1p3mhp',
  'MIA': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/lits6p8ycth9io9u6dhy',
  'MIN': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/teguylrnqqmfcwxvcmmz',
  'NE': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/moyfxx3dq5pio4aiftnc',
  'NO': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/sk7jkwbuuvmwdfm72cy1',
  'NYG': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/t6mhdmgizi6qhndh8b9p',
  'NYJ': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/ekijosiae96gektbo4iw',
  'PHI': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/puhrqgj71gobgdkdo6uq',
  'PIT': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/xujg9t3escthaxzswjkk',
  'SF': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/dxibuyxbk0b9ua5ih9hn',
  'SFO': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/dxibuyxbk0b9ua5ih9hn',
  'SEA': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/lcgaue6nzwsmhz7h9zng',
  'TB': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/v8uqiualryypwqgvwcih',
  'TEN': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/pln44vuzugjgipyidsre',
  'WAS': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/xymxwrxtyj9fhaemhdyd',
  'WSH': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/xymxwrxtyj9fhaemhdyd',
  // Lowercase variations found in database
  'ari': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/u9fltoslqdsyao8cpm0k',
  'atl': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/d8m7hzpsbrl6pnqht8op',
  'bal': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/ucsdijmddsqcj1i0nmur',
  'buf': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/giphcy6ie9mxbnldntsf',
  'car': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/ervfzgrqdqpkfcjhu8jq',
  'chi': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/ra0poua3hivselqbgcbs',
  'cin': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/okxpteoliyayufypqalq',
  'cle': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/fgbn8acp4opvyxk13dcy',
  'dal': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/ieid8hoygzdlmzo0yhqr',
  'den': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/t2jwlmj1tmpzcqzf2eav',
  'det': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/ocvxwnapdvwevupe4tpr',
  'gnb': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/k5oxnyitwseuo27mnod9',
  'hou': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/bpx2n7s8m4u2pz8dbu5m',
  'ind': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/keenyn6qtrzngbcq8bre',
  'jax': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/qykmj6xgtzpyc7xlzyra',
  'kan': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/ujdzcqep1oxcgbwgz3bz',
  'lac': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/dhfidtn8jrumakbogeu4',
  'lar': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/ayvngv0oygf5ym1p3mhp',
  'mia': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/lits6p8ycth9io9u6dhy',
  'min': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/teguylrnqqmfcwxvcmmz',
  'nor': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/sk7jkwbuuvmwdfm72cy1',
  'nyg': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/t6mhdmgizi6qhndh8b9p',
  'nyj': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/ekijosiae96gektbo4iw',
  'phi': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/puhrqgj71gobgdkdo6uq',
  'pit': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/xujg9t3escthaxzswjkk',
  'rai': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/gzcojbzcyjgubgyb6xf2',
  'sea': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/lcgaue6nzwsmhz7h9zng',
  'sfo': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/dxibuyxbk0b9ua5ih9hn',
  'tam': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/v8uqiualryypwqgvwcih',
  'ten': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/pln44vuzugjgipyidsre',
  'was': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/xymxwrxtyj9fhaemhdyd',
  // Additional team codes from your list
  'crd': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/u9fltoslqdsyao8cpm0k', // Arizona Cardinals
  'rav': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/ucsdijmddsqcj1i0nmur', // Baltimore Ravens
  'htx': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/bpx2n7s8m4u2pz8dbu5m', // Houston Texans
  'clt': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/keenyn6qtrzngbcq8bre', // Indianapolis Colts
  'sdg': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/dhfidtn8jrumakbogeu4', // Los Angeles Chargers
  'ram': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/ayvngv0oygf5ym1p3mhp', // Los Angeles Rams
  'nwe': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/moyfxx3dq5pio4aiftnc', // New England Patriots
  'oti': 'https://static.www.nfl.com/image/private/t_headshot_desktop/league/pln44vuzugjgipyidsre', // Tennessee Titans
};
