// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sscbiguykvehveaepbij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzY2JpZ3V5a3ZlaHZlYWVwYmlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NDI0NDgsImV4cCI6MjA2NDAxODQ0OH0.AxiW956Gemt87ksUlv5qVED52gIcFSkI9xut5AGUx-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);